### ISSUE TITLE
(maybe) bug: Fhdo does not include current line

### ISSUE THREAD

**Issue by willruggiano** [Furkanzmc/firvish.nvim#11]
See my fix here: https://github.com/willruggiano/firvish.nvim/commit/62dba8116a2356c23daad7c0d6715616491146a6

If you think this is a legitimate bug I can submit a PR

**Comment by Furkanzmc** [comment]
This is a good catch. Admittedly, I haven't used `:Fhdo` in a while so I haven't noticed. A PR would be nice, thank you!
